# insert regions
INSERT INTO regions (region_id, region_name) VALUES (1, "Винницкая область");
INSERT INTO regions (region_id, region_name) VALUES (2, "Волынская область");
INSERT INTO regions (region_id, region_name) VALUES (3, "Днепропетровская область");
INSERT INTO regions (region_id, region_name) VALUES (4, "Донецкая область");
INSERT INTO regions (region_id, region_name) VALUES (5, "Житомирская область");
INSERT INTO regions (region_id, region_name) VALUES (6, "Закарпатская область");
INSERT INTO regions (region_id, region_name) VALUES (7, "Запорожская область");
INSERT INTO regions (region_id, region_name) VALUES (8, "Ивано-Франковская область");
INSERT INTO regions (region_id, region_name) VALUES (9, "Киевская область");
INSERT INTO regions (region_id, region_name) VALUES (10, "Кировоградская область");
INSERT INTO regions (region_id, region_name) VALUES (11, "Луганская область");
INSERT INTO regions (region_id, region_name) VALUES (12, "Львовская область");
INSERT INTO regions (region_id, region_name) VALUES (13, "Николаевская область");
INSERT INTO regions (region_id, region_name) VALUES (14, "Одесская область");
INSERT INTO regions (region_id, region_name) VALUES (15, "Полтавская область");
INSERT INTO regions (region_id, region_name) VALUES (16, "Ровенская область");
INSERT INTO regions (region_id, region_name) VALUES (17, "Сумская область");
INSERT INTO regions (region_id, region_name) VALUES (18, "Тернопольская область");
INSERT INTO regions (region_id, region_name) VALUES (19, "Харьковская область");
INSERT INTO regions (region_id, region_name) VALUES (20, "Херсонская область");
INSERT INTO regions (region_id, region_name) VALUES (21, "Хмельницкая область");
INSERT INTO regions (region_id, region_name) VALUES (22, "Черкасская область");
INSERT INTO regions (region_id, region_name) VALUES (23, "Черниговская область");
INSERT INTO regions (region_id, region_name) VALUES (24, "Черновицкая область");
INSERT INTO regions (region_id, region_name) VALUES (25, "Автономная Республика Крым");

# insert cities
INSERT INTO cities (city_id, region_id, city_name, is_center) VALUES (1, 1, "Винница", TRUE);
INSERT INTO cities (city_id, region_id, city_name, is_center) VALUES (2, 2, "Луцк", TRUE);
INSERT INTO cities (city_id, region_id, city_name, is_center) VALUES (3, 3, "Днепропетровск", TRUE);
INSERT INTO cities (city_id, region_id, city_name, is_center) VALUES (4, 4, "Донецк", TRUE);
INSERT INTO cities (city_id, region_id, city_name, is_center) VALUES (5, 5, "Житомир", TRUE);
INSERT INTO cities (city_id, region_id, city_name, is_center) VALUES (6, 6, "Ужгород", TRUE);
INSERT INTO cities (city_id, region_id, city_name, is_center) VALUES (7, 7, "Запорожье", TRUE);
INSERT INTO cities (city_id, region_id, city_name, is_center) VALUES (8, 8, "Ивано-Франковск", TRUE);
INSERT INTO cities (city_id, region_id, city_name, is_center) VALUES (9, 9, "Киев", TRUE);
INSERT INTO cities (city_id, region_id, city_name, is_center) VALUES (10, 10, "Кировоград", TRUE);
INSERT INTO cities (city_id, region_id, city_name, is_center) VALUES (11, 11, "Луганск", TRUE);
INSERT INTO cities (city_id, region_id, city_name, is_center) VALUES (12, 12, "Львов", TRUE);
INSERT INTO cities (city_id, region_id, city_name, is_center) VALUES (13, 13, "Николаев", TRUE);
INSERT INTO cities (city_id, region_id, city_name, is_center) VALUES (14, 14, "Одесса", TRUE);
INSERT INTO cities (city_id, region_id, city_name, is_center) VALUES (15, 15, "Полтава", TRUE);
INSERT INTO cities (city_id, region_id, city_name, is_center) VALUES (16, 16, "Ровно", TRUE);
INSERT INTO cities (city_id, region_id, city_name, is_center) VALUES (17, 17, "Сумы", TRUE);
INSERT INTO cities (city_id, region_id, city_name, is_center) VALUES (18, 18, "Тернополь", TRUE);
INSERT INTO cities (city_id, region_id, city_name, is_center) VALUES (19, 19, "Харьков", TRUE);
INSERT INTO cities (city_id, region_id, city_name, is_center) VALUES (20, 20, "Херсон", TRUE);
INSERT INTO cities (city_id, region_id, city_name, is_center) VALUES (21, 21, "Хмельницкий", TRUE);
INSERT INTO cities (city_id, region_id, city_name, is_center) VALUES (22, 22, "Черкассы", TRUE);
INSERT INTO cities (city_id, region_id, city_name, is_center) VALUES (23, 23, "Чернигов", TRUE);
INSERT INTO cities (city_id, region_id, city_name, is_center) VALUES (24, 24, "Черновцы", TRUE);
INSERT INTO cities (city_id, region_id, city_name, is_center) VALUES (25, 25, "Симферополь", TRUE);